// import pedroManuel from "../assets/PedroOlavarrieta.jpeg";


export interface VolunteerMember {
  id: number;
  name: string;
  role: string;
  initials: string;
  color: string;
  size: "large" | "medium" | "small";
  // Para usar imagen local: import foto from "../assets/volunteers/nombre.jpg" → imageUrl: foto
  // Para usar URL externa: imageUrl: "https://..."
  // Para mostrar solo iniciales: omite imageUrl o déjalo como undefined
  imageUrl?: string;
}

export const VOLUNTEER_MEMBERS: VolunteerMember[] = [
  {
    id: 1,
    name: "Pedro Manuel Olavarrieta Álvarez",
    role: "Voluntario",
    initials: "PM",
    color: "#f59e0b",
    size: "large",
  },
  {
    id: 2,
    name: "Adonis Gabriel Brito Guzmán",
    role: "Voluntario",
    initials: "AG",
    color: "#fb923c",
    size: "small",
  },
  {
    id: 3,
    name: "Weldris Natalia Gil Olivares",
    role: "Voluntario",
    initials: "WN",
    color: "#fbbf24",
    size: "medium",
  },
  {
    id: 4,
    name: "Josmeiry Nashaly Torres Jáquez",
    role: "Voluntario",
    initials: "JN",
    color: "#f97316",
    size: "small",
  },
  {
    id: 5,
    name: "Joshua Sanquintin De Óleo",
    role: "Voluntario",
    initials: "JS",
    color: "#f59e0b",
    size: "large",
  },
  {
    id: 6,
    name: "Sury Elibeth Rodríguez Taveras",
    role: "Voluntario",
    initials: "SE",
    color: "#fbbf24",
    size: "small",
  },
  {
    id: 7,
    name: "Lia Victoria Bonilla Nadal",
    role: "Voluntario",
    initials: "LV",
    color: "#fb923c",
    size: "medium",
  },
  {
    id: 8,
    name: "Santiago André Contreras De Nobrega",
    role: "Voluntario",
    initials: "SA",
    color: "#f59e0b",
    size: "small",
  },
  {
    id: 9,
    name: "Amin Ariel Alvarado Sena",
    role: "Voluntario",
    initials: "AA",
    color: "#f97316",
    size: "large",
  },  {
    id: 10,
    name: "Arturo Alejandro Vallejo Ramirez",
    role: "Voluntario",
    initials: "AA",
    color: "#fb923c",
    size: "small",
  },
  {
    id: 11,
    name: "Alyha Giovanna Peña Inoa",
    role: "Voluntario",
    initials: "AG",
    color: "#fbbf24",
    size: "medium",
  },
  {
    id: 12,
    name: "Kin Emir Lau Blanco",
    role: "Voluntario",
    initials: "KE",
    color: "#f97316",
    size: "small",
  },
  {
    id: 13,
    name: "Nicole Marie Ovalles Padilla",
    role: "Voluntario",
    initials: "NM",
    color: "#f59e0b",
    size: "large",
  },
  {
    id: 14,
    name: "Emely Samboy Payano",
    role: "Voluntario",
    initials: "ES",
    color: "#fb923c",
    size: "small",
  },
  {
    id: 15,
    name: "Chadhays Lopez",
    role: "Voluntario",
    initials: "CL",
    color: "#fbbf24",
    size: "medium",
  },
  {
    id: 16,
    name: "Gregoris Raúl Medrano Berigüete",
    role: "Voluntario",
    initials: "GR",
    color: "#f97316",
    size: "small",
  },
  {
    id: 17,
    name: "Julio A. Méndez Nina",
    role: "Voluntario",
    initials: "JA",
    color: "#f59e0b",
    size: "large",
  },
  {
    id: 18,
    name: "Lucía Natalia Lama Pepén",
    role: "Voluntario",
    initials: "LN",
    color: "#fb923c",
    size: "small",
  },
  {
    id: 19,
    name: "Elizabeth Georgina Corsino Tejada",
    role: "Voluntario",
    initials: "EG",
    color: "#fbbf24",
    size: "medium",
  },
  {
    id: 20,
    name: "Bryan Steven Vargas",
    role: "Voluntario",
    initials: "BS",
    color: "#f97316",
    size: "small",
  },
  {
    id: 21,
    name: "Yaniel Rafael Contreras Ramírez",
    role: "Voluntario",
    initials: "YR",
    color: "#f59e0b",
    size: "large",
  },
  {
    id: 22,
    name: "Camila Durán Arias",
    role: "Voluntario",
    initials: "CD",
    color: "#fb923c",
    size: "small",
  },
  {
    id: 23,
    name: "Sarah Santos",
    role: "Voluntario",
    initials: "SS",
    color: "#fbbf24",
    size: "medium",
  },
  {
    id: 24,
    name: "Fabiola Valentina Escobar Ascanio",
    role: "Voluntario",
    initials: "FV",
    color: "#f97316",
    size: "small",
  },
  {
    id: 25,
    name: "Lia López Castro",
    role: "Voluntario",
    initials: "LL",
    color: "#f59e0b",
    size: "large",
  },
  {
    id: 26,
    name: "Laury Zapata Rondón",
    role: "Voluntario",
    initials: "LZ",
    color: "#fb923c",
    size: "small",
  },
  {
    id: 27,
    name: "Ashley Esther Martinez Santana",
    role: "Voluntario",
    initials: "AE",
    color: "#fbbf24",
    size: "medium",
  },
  {
    id: 28,
    name: "Mercedes Sylvia Pinchinat",
    role: "Voluntario",
    initials: "MS",
    color: "#f97316",
    size: "small",
  },
  {
    id: 29,
    name: "Salim Alberto Ureña Villa",
    role: "Voluntario",
    initials: "SA",
    color: "#f59e0b",
    size: "large",
  },
  {
    id: 30,
    name: "Eliana Luciano Báez",
    role: "Voluntario",
    initials: "EL",
    color: "#fb923c",
    size: "small",
  },
  {
    id: 31,
    name: "Eliana Marit Rodríguez Vallejo",
    role: "Voluntario",
    initials: "EM",
    color: "#fbbf24",
    size: "medium",
  },
  {
    id: 32,
    name: "Laura Marianne Méndez Hernández",
    role: "Voluntario",
    initials: "LM",
    color: "#f97316",
    size: "small",
  },
  {
    id: 33,
    name: "Maria Del Mar Rodriguez Baba",
    role: "Voluntario",
    initials: "MD",
    color: "#f59e0b",
    size: "large",
  },
  {
    id: 34,
    name: "Perla Lucero Franco Santana",
    role: "Voluntario",
    initials: "PL",
    color: "#fb923c",
    size: "small",
  },
  {
    id: 35,
    name: "María Fernanda Pinedo María",
    role: "Voluntario",
    initials: "MF",
    color: "#fbbf24",
    size: "medium",
  },
  {
    id: 36,
    name: "Aisha Pamela Núñez Lara",
    role: "Voluntario",
    initials: "AP",
    color: "#f97316",
    size: "small",
  },
  {
    id: 37,
    name: "Sara Elena Acevedo Uceta",
    role: "Voluntario",
    initials: "SE",
    color: "#f59e0b",
    size: "large",
  },
  {
    id: 38,
    name: "Sarah Agelan",
    role: "Voluntario",
    initials: "SA",
    color: "#fb923c",
    size: "small",
  },
  {
    id: 39,
    name: "Cris Almeris Zanellato Lorenzo",
    role: "Voluntario",
    initials: "CA",
    color: "#fbbf24",
    size: "medium",
  },
  {
    id: 40,
    name: "Camila Mariel Casado Martínez",
    role: "Voluntario",
    initials: "CM",
    color: "#f97316",
    size: "small",
  },
  {
    id: 41,
    name: "Leiron Ogando Ramírez",
    role: "Voluntario",
    initials: "LO",
    color: "#f59e0b",
    size: "large",
  },
  {
    id: 42,
    name: "Melody Cristal Matos Reynoso",
    role: "Voluntario",
    initials: "MC",
    color: "#fb923c",
    size: "small",
  },
  {
    id: 43,
    name: "Jean Marco Yermenos Linares",
    role: "Voluntario",
    initials: "JM",
    color: "#fbbf24",
    size: "medium",
  },
  {
    id: 44,
    name: "Sara María Morillo Fernández",
    role: "Voluntario",
    initials: "SM",
    color: "#f97316",
    size: "small",
  },
  {
    id: 45,
    name: "David Batista Rojas",
    role: "Voluntario",
    initials: "DB",
    color: "#f59e0b",
    size: "large",
  },
  {
    id: 46,
    name: "Anne Marie Amarante Rojas",
    role: "Voluntario",
    initials: "AM",
    color: "#fb923c",
    size: "small",
  },
  {
    id: 47,
    name: "Chantal Rodríguez",
    role: "Voluntario",
    initials: "CR",
    color: "#fbbf24",
    size: "medium",
  },
  {
    id: 48,
    name: "Ana Paloma Medina Suárez",
    role: "Voluntario",
    initials: "AP",
    color: "#f97316",
    size: "small",
  },
  {
    id: 49,
    name: "Keyla Polanco Díaz",
    role: "Voluntario",
    initials: "KP",
    color: "#f59e0b",
    size: "large",
  },
  {
    id: 50,
    name: "Franmy Mena De Jesús",
    role: "Voluntario",
    initials: "FM",
    color: "#fb923c",
    size: "small",
  },
  {
    id: 51,
    name: "Adrián Ramses Ureña Berroa",
    role: "Voluntario",
    initials: "AR",
    color: "#fbbf24",
    size: "medium",
  },
  {
    id: 52,
    name: "Luis Enrique Peña Tejada",
    role: "Voluntario",
    initials: "LE",
    color: "#f97316",
    size: "small",
  },
  {
    id: 53,
    name: "Lia Isabel Guido Mora",
    role: "Voluntario",
    initials: "LI",
    color: "#f59e0b",
    size: "large",
  },
  {
    id: 54,
    name: "Jhoscarlin Zadit Pérez Roa",
    role: "Voluntario",
    initials: "JZ",
    color: "#fb923c",
    size: "small",
  },
  {
    id: 55,
    name: "Maryelin García Muñoz",
    role: "Voluntario",
    initials: "MG",
    color: "#fbbf24",
    size: "medium",
  },
  {
    id: 56,
    name: "Roselin Mary Pineda Torres",
    role: "Voluntario",
    initials: "RM",
    color: "#f97316",
    size: "small",
  },
  {
    id: 57,
    name: "Albalexa Villavisar García",
    role: "Voluntario",
    initials: "AV",
    color: "#f59e0b",
    size: "large",
  },
  {
    id: 58,
    name: "Lucy Annie Matos De Los Santos",
    role: "Voluntario",
    initials: "LA",
    color: "#fb923c",
    size: "small",
  },
  {
    id: 59,
    name: "Yoleisy Dahiana Guerrero Lorenzo",
    role: "Voluntario",
    initials: "YD",
    color: "#fbbf24",
    size: "medium",
  },
  {
    id: 60,
    name: "Julissa Peña Mercedes",
    role: "Voluntario",
    initials: "JP",
    color: "#f97316",
    size: "small",
  },
  {
    id: 61,
    name: "Celinet Brito Castillo",
    role: "Voluntario",
    initials: "CB",
    color: "#f59e0b",
    size: "large",
  },
  {
    id: 62,
    name: "Zara Nova Urbaez",
    role: "Voluntario",
    initials: "ZN",
    color: "#fb923c",
    size: "small",
  },
  {
    id: 63,
    name: "Ambar Marie Ortiz Hernández",
    role: "Voluntario",
    initials: "AM",
    color: "#fbbf24",
    size: "medium",
  },
  {
    id: 64,
    name: "Elaine Ogando Cipion",
    role: "Voluntario",
    initials: "EO",
    color: "#f97316",
    size: "small",
  },
  {
    id: 65,
    name: "Lia Bulut",
    role: "Voluntario",
    initials: "LB",
    color: "#f59e0b",
    size: "large",
  },
  {
    id: 66,
    name: "Valeria Padrón Saud",
    role: "Voluntario",
    initials: "VP",
    color: "#fb923c",
    size: "small",
  },
  {
    id: 67,
    name: "Alba Delia Martinez Montero",
    role: "Voluntario",
    initials: "AD",
    color: "#fbbf24",
    size: "medium",
  },
  {
    id: 68,
    name: "Jasmali Rodríguez Durán",
    role: "Voluntario",
    initials: "JR",
    color: "#f97316",
    size: "small",
  },
  {
    id: 69,
    name: "Natalia Angomás Mascarell",
    role: "Voluntario",
    initials: "NA",
    color: "#f59e0b",
    size: "large",
  },
];
